-- Seed static content: profiles, modifications, anomalies, categories

-- Profiles
insert into profiles (id, name, style, passive_description, active_description, flavor) values
('chronotyp',      'Chronotyp',      'czas',       'Masz +1 sekundę na każde pytanie.',                                                                                                   'Raz na Test dodaj sobie +4 sekundy do aktualnego pytania. Możesz użyć przed udzieleniem odpowiedzi.',                                                                    '„Czas nie płynie szybciej. Ty płyniesz wolniej."'),
('katalizator',    'Katalizator',    'modyfikacje','Pierwsza poprawna odpowiedź po wybraniu każdej Modyfikacji daje dodatkowe +40 pkt.',                                                  'Raz na Test, jeśli masz co najmniej jedną aktywną Modyfikację, Twoja następna poprawna odpowiedź daje dodatkowe +60 pkt.',                                               '„Reakcja zaczyna się dopiero po kontakcie z decyzją."'),
('stabilizator',   'Stabilizator',   'obrona',     'Pierwsze 2 błędne odpowiedzi w Teście mają karę zmniejszoną o 50%.',                                                                 'Raz na Test anuluj bazową karę za błędną odpowiedź w aktualnym pytaniu. Nie anuluje dodatkowych kar z Modyfikacji.',                                                     '„Nie zapobiega błędom. Zmniejsza rozmiar krateru."'),
('spektrometr',    'Spektrometr',    'informacja', 'Przed każdym pytaniem widzisz kategorię 2 sekundy wcześniej niż inni gracze.',                                                       '2 razy na Test zobacz poziom trudności aktualnego pytania przed odpowiedzią.',                                                                                           '„Nie zna odpowiedzi. Zna kształt problemu."'),
('replikant',      'Replikant',      'kopiowanie', 'Po każdej rundzie draftu widzisz, którą Modyfikację wybrał aktualny lider.',                                                          'Raz na Test skopiuj aktywną Modyfikację wybranego gracza. Skopiowana Modyfikacja ma 50% wartości punktowych/procentowych. Czas działania bez zmian.',                    '„Oryginał był tylko pierwszą wersją."'),
('operator-pola',  'Operator Pola',  'anty-pvp',   'Negatywne efekty PvP skierowane w Ciebie trwają o 1 pytanie krócej. Minimum to 1 pytanie.',                                          'Raz na Test zablokuj jeden negatywny efekt PvP skierowany w Ciebie. Możesz użyć po zobaczeniu efektu.',                                                                  '„Pole nie jest bezpieczne. Jest kontrolowane."'),
('synapsa',        'Synapsa',        'seria',      'Za każdą serię 3 poprawnych odpowiedzi z rzędu dostajesz dodatkowe +60 pkt.',                                                         'Raz na Test zabezpiecz aktualną serię. Następna błędna odpowiedź nie resetuje serii.',                                                                                   '„Jedna odpowiedź to impuls. Trzy to wzorzec."'),
('null',           'Null',           'reset',      'Raz na Test pierwsza błędna odpowiedź nie daje bazowej kary punktowej.',                                                              'Raz na Test usuń jeden aktywny negatywny efekt PvP. Nie usuwa kosztów Modyfikacji wybranych przez Ciebie.',                                                              '„Brak sygnału też jest wynikiem."'),
('wektor',         'Wektor',         'szybkość',   'Odpowiedź w pierwszych 4 sekundach daje dodatkowe +25 pkt, jeśli jest poprawna.',                                                     'Raz na Test podwój swój bonus za szybkość w aktualnym pytaniu. Maksymalny dodatkowy zysk z tej aktywnej umiejętności: +50 pkt.',                                         '„Kierunek jest ważny. Prędkość też."'),
('archiwista',     'Archiwista',     'kategorie',  'Jeśli dwa pytania z rzędu są z tej samej kategorii, poprawna odpowiedź w drugim pytaniu daje dodatkowe +50 pkt.',                    'Raz na Test przed pytaniem wybierz jedną z dwóch kategorii. Następne pytanie będzie z wybranej kategorii dla wszystkich graczy.',                                         '„Wszystko już gdzieś było. Trzeba tylko wiedzieć gdzie."'),
('fraktal',        'Fraktal',        'comeback',   'Jeśli jesteś w dolnej połowie tabeli, poprawna odpowiedź daje dodatkowe +30 pkt.',                                                    'Raz na Test, jeśli jesteś na ostatnim miejscu, następna poprawna odpowiedź daje dodatkowe +100 pkt.',                                                                    '„Każda porażka zawiera mniejszą wersję powrotu."'),
('obserwator',     'Obserwator',     'informacja', 'Po 5 sekundach pytania widzisz, ilu graczy już odpowiedziało.',                                                                       'Raz na Test po 6 sekundach pytania zobacz, ile osób wybrało każdą odpowiedź. Twoje punkty za to pytanie są zmniejszone o 30%.',                                          '„Pomiar zmienia wynik. Czasem warto."'),
('przekaznik',     'Przekaźnik',     'wydłużanie', 'Pierwsza Modyfikacja czasowa, którą wybierzesz, trwa o 1 pytanie dłużej.',                                                            'Raz na Test wydłuż aktualnie aktywną Modyfikację czasową o 1 pytanie. Nie działa na Modyfikacje jednorazowe.',                                                           '„Sygnał nie ginie. Zmienia nośnik."'),
('horyzont',       'Horyzont',       'końcówka',   'W pytaniach 10–12 Twoje poprawne odpowiedzi dają +20% punktów.',                                                                      'Raz na Test przed pytaniem 10, 11 albo 12 zwiększ swój bonus końcowy do +40% na jedno pytanie.',                                                                         '„Najważniejsze dane pojawiają się przy granicy."'),
('izolator',       'Izolator',       'odporność',  'Pierwszy negatywny efekt PvP w Teście nie działa na Ciebie.',                                                                         'Raz na Test przez następne 2 pytania nie możesz być celem efektów PvP.',                                                                                                 '„Próbka została odseparowana od chaosu."');

-- Modifications
insert into modifications (id, name, type, effect_description, duration_description, flavor) values
('prog-pewnosci',         'Próg Pewności',          'Ryzyko',                'Przez następne 2 pytania: poprawna odpowiedź daje +50% punktów, błędna odpowiedź zabiera dodatkowe -75 pkt.',                                                                                      '2 pytania',                                  '„Instytut zaleca pewność. Instytut nie refunduje pomyłek."'),
('opozniona-reakcja',     'Opóźniona Reakcja',      'Skalowanie',            'Nie odpowiadasz na następne 2 pytania. Od kolejnego pytania do końca Testu Twoje poprawne odpowiedzi dają +25% punktów.',                                                                          'Do końca Testu po zakończeniu blokady',      '„Brak reakcji też jest reakcją. Tylko później."'),
('redukcja-szumu',        'Redukcja Szumu',          'Podpowiedź',            '2 razy do końca Testu możesz usunąć jedną błędną odpowiedź. Działa tylko w pytaniach single_choice.',                                                                                              'Do wykorzystania 2 razy',                    '„Nie pokazuje prawdy. Usuwa część kłamstw."'),
('kalibracja-odruchu',    'Kalibracja Odruchu',      'Szybkość',              'Do końca Testu odpowiedź w pierwszych 4 sekundach daje dodatkowe +35 pkt, jeśli jest poprawna.',                                                                                                   'Do końca Testu',                             '„Odruch zatwierdzony. Rozsądek w kolejce."'),
('bezpiecznik',           'Bezpiecznik',             'Obrona',                'Pierwsza błędna odpowiedź po wybraniu tej Modyfikacji nie daje bazowej kary punktowej.',                                                                                                            'Do aktywacji albo do końca Testu',           '„Pomyłka została przewidziana. To niepokojące."'),
('reakcja-lancuchowa',    'Reakcja Łańcuchowa',      'Seria',                 'Do końca Testu każda kolejna poprawna odpowiedź z rzędu daje narastający bonus: 2. z rzędu +20 pkt, 3. z rzędu +40 pkt, 4. i kolejne +60 pkt. Błędna odpowiedź resetuje bonus do 0.',             'Do końca Testu',                             '„Jeden impuls to przypadek. Cztery to procedura."'),
('akcelerator-decyzji',   'Akcelerator Decyzji',     'Ryzyko / czas',         'Przez następne 3 pytania: masz -3 sekundy na odpowiedź, poprawna odpowiedź daje +40% punktów.',                                                                                                   '3 pytania',                                  '„Szybciej nie znaczy lepiej. Ale czasem wystarczy."'),
('stabilizacja-wyniku',   'Stabilizacja Wyniku',     'Obrona',                'Przez następne 4 pytania błędna odpowiedź zabiera o 50 pkt mniej. Redukcja nie może zmienić kary w bonus.',                                                                                        '4 pytania',                                  '„Upadek kontrolowany nadal jest upadkiem."'),
('skan-trudnosci',        'Skan Trudności',          'Informacja',            'Do końca Testu przed każdym pytaniem widzisz poziom trudności: łatwe / średnie / trudne.',                                                                                                         'Do końca Testu',                             '„Nie mówi, co jest prawdą. Mówi, jak bardzo zaboli."'),
('interferencja-lidera',  'Interferencja Lidera',    'PvP',                   'Gracz na 1. miejscu ma -3 sekundy na odpowiedź w następnym pytaniu.',                                                                                                                               '1 pytanie',                                  '„Zakłócenie dotyczy wyłącznie obiektu o najwyższej energii."'),
('zaklocenie-kanalu',     'Zakłócenie Kanału',       'PvP',                   'Wybrany gracz traci 30% bonusu za szybkość w następnych 2 pytaniach.',                                                                                                                              '2 pytania',                                  '„Sygnał dotarł. Tylko nie tam, gdzie trzeba."'),
('transfer-impulsu',      'Transfer Impulsu',        'PvP / szybkość',        'Przez następne 3 pytania, jeśli odpowiesz poprawnie szybciej niż aktualny lider, dostajesz dodatkowe +40 pkt.',                                                                                    '3 pytania',                                  '„Energia lidera została uznana za zasób wspólny."'),
('odwrocenie-polaryzacji','Odwrócenie Polaryzacji',  'Obrona / PvP',          'Następny negatywny efekt PvP skierowany w Ciebie wraca do nadawcy. Efekt działa tylko raz.',                                                                                                       'Do aktywacji albo do końca Testu',           '„Kierunek zakłócenia został skorygowany."'),
('druga-proba',           'Druga Próba',             'Podpowiedź',            'Raz do końca Testu możesz zmienić odpowiedź przed końcem czasu. Jeśli po zmianie odpowiedź jest poprawna, dostajesz tylko 50% punktów za to pytanie.',                                             '1 użycie',                                   '„Instytut dopuszcza wahanie. Z rabatem."'),
('petla-testowa',         'Pętla Testowa',           'Obrona / czas',         'Następna błędna odpowiedź nie daje bazowej kary, a w kolejnym pytaniu masz +3 sekundy.',                                                                                                           'Do aktywacji albo do końca Testu',           '„Błąd zapisano jako próbę wstępną."'),
('odbicie-sygnalu',       'Odbicie Sygnału',         'Comeback / PvP',        'Po otrzymaniu negatywnego efektu PvP Twoja następna poprawna odpowiedź daje dodatkowe +75 pkt.',                                                                                                   'Do aktywacji albo do końca Testu',           '„Zakłócenie wróciło w formie danych."'),
('kompensacja-deficytu',  'Kompensacja Deficytu',    'Comeback',              'Do końca Testu, jeśli jesteś w dolnej połowie tabeli, poprawna odpowiedź daje +25% punktów.',                                                                                                      'Do końca Testu',                             '„Niski wynik zwiększa podatność na korektę."'),
('proba-krytyczna',       'Próba Krytyczna',         'Ryzyko',                'W następnym pytaniu: poprawna odpowiedź daje dodatkowe +100 pkt, błędna odpowiedź zabiera dodatkowe -100 pkt.',                                                                                    '1 pytanie',                                  '„Parametry testu przekroczyły zdrowy rozsądek."'),
('tarcza-fazowa',         'Tarcza Fazowa',           'Obrona',                'Przez następne 2 pytania nie możesz być celem efektów PvP.',                                                                                                                                       '2 pytania',                                  '„Obiekt obecny. Kontakt niemożliwy."'),
('analiza-wstepna',       'Analiza Wstępna',         'Informacja',            'Przez następne 4 pytania widzisz kategorię 3 sekundy przed rozpoczęciem pytania.',                                                                                                                 '4 pytania',                                  '„Przygotowanie nie jest odpowiedzią. Ale pomaga."'),
('wzmocnienie-sygnalu',   'Wzmocnienie Sygnału',     'Punkty',                'Przez następne 3 pytania poprawna odpowiedź daje dodatkowe +30 pkt.',                                                                                                                              '3 pytania',                                  '„Sygnał podniesiony powyżej normy."'),
('nadpisanie-wyniku',     'Nadpisanie Wyniku',       'Ryzyko / odroczenie',   'Następna poprawna odpowiedź zapisuje dodatkowe +100 pkt w buforze. Punkty zostaną wypłacone po 2 kolejnych pytaniach, jeśli w tym czasie nie odpowiesz błędnie. Błąd usuwa bufor.',                'Do rozliczenia bufora',                       '„Wynik zostanie zatwierdzony po kontroli."'),
('cichy-protokol',        'Cichy Protokół',          'Informacja / comeback',  'Przez następne 2 pytania tabela wyników jest ukryta dla wszystkich. Jeśli nie jesteś liderem, Twoja poprawna odpowiedź daje dodatkowe +40 pkt.',                                                   '2 pytania',                                  '„Brak danych zmniejsza panikę. Czasem."'),
('rezonans-koncowy',      'Rezonans Końcowy',        'Końcówka',              'W pytaniach 10–12, jeśli nie jesteś na 1. miejscu, poprawna odpowiedź daje +30% punktów.',                                                                                                         'Do końca Testu, działa tylko w pytaniach 10–12', '„Im bliżej końca, tym głośniej drga wynik."');

-- Anomalies
insert into anomalies (id, name, effect_description) values
('niestabilne-pole',    'Niestabilne Pole',    'Wszyscy gracze mają -2 sekundy na odpowiedź w tym pytaniu.'),
('wzmocnienie-sygnalu', 'Wzmocnienie Sygnału', 'Maksymalny bonus za szybkość w tym pytaniu wynosi +75 pkt zamiast +50 pkt.'),
('proba-kontrolna',     'Próba Kontrolna',     'W tym pytaniu nie działają negatywne efekty PvP.'),
('fluktuacja-wyniku',   'Fluktuacja Wyniku',   'W tym pytaniu poprawna odpowiedź daje +20% punktów, a błędna odpowiedź zabiera dodatkowe -25 pkt.'),
('cisza-pomiarowa',     'Cisza Pomiarowa',     'Po tym pytaniu tabela wyników jest ukryta do rozpoczęcia następnego pytania.'),
('przesuniecie-fazowe', 'Przesunięcie Fazowe', 'W tym pytaniu bonus za szybkość nie działa. Poprawna odpowiedź daje bazowo +125 pkt zamiast +100 pkt.');

-- Seed categories
insert into categories (name) values
('Historia'),
('Nauka'),
('Geografia'),
('Kultura i sztuka'),
('Sport'),
('Technologia'),
('Przyroda'),
('Matematyka');
